package api

import (
	"net/http"

	"github.com/erraggy/oastools/builder"
)

// registerOperations adds all API operations to the ServerBuilder.
func (h *Handler) registerOperations(srv *builder.ServerBuilder) {
	// Health check
	srv.AddOperation(http.MethodGet, "/health",
		builder.WithOperationID("getHealth"),
		builder.WithSummary("Health check endpoint"),
		builder.WithTags("system"),
		builder.WithResponse(http.StatusOK, HealthResponse{},
			builder.WithResponseDescription("Service health status"),
		),
		builder.WithHandler(h.handleHealth),
	)

	// GET /api/spec - returns this API's OpenAPI specification
	srv.AddOperation(http.MethodGet, "/api/spec",
		builder.WithOperationID("getAPISpec"),
		builder.WithSummary("Get this API's OpenAPI specification"),
		builder.WithTags("system"),
		builder.WithResponse(http.StatusOK, nil,
			builder.WithResponseDescription("OpenAPI 3.2 specification in YAML or JSON"),
		),
		builder.WithHandler(h.handleSpec),
	)

	// POST /api/validate - validate an OpenAPI specification
	srv.AddOperation(http.MethodPost, "/api/validate",
		builder.WithOperationID("validateSpec"),
		builder.WithSummary("Validate an OpenAPI specification"),
		builder.WithDescription("Validates an OpenAPI specification and returns a detailed validation report with errors and warnings."),
		builder.WithTags("operations"),
		builder.WithFileParam("spec",
			builder.WithParamDescription("OpenAPI specification file (JSON or YAML)"),
			builder.WithParamRequired(true),
		),
		builder.WithResponse(http.StatusOK, ValidateResponse{},
			builder.WithResponseDescription("Validation result"),
		),
		builder.WithResponse(http.StatusBadRequest, ErrorResponse{},
			builder.WithResponseDescription("Invalid request or unparseable file"),
		),
		builder.WithHandler(h.handleValidate),
	)

	// POST /api/convert - convert an OpenAPI specification to a different version
	srv.AddOperation(http.MethodPost, "/api/convert",
		builder.WithOperationID("convertSpec"),
		builder.WithSummary("Convert an OpenAPI specification"),
		builder.WithDescription("Converts an OpenAPI specification between versions (2.0, 3.0, 3.1, 3.2)."),
		builder.WithTags("operations"),
		builder.WithFileParam("spec",
			builder.WithParamDescription("OpenAPI specification file (JSON or YAML)"),
			builder.WithParamRequired(true),
		),
		builder.WithFormParam("target", "string",
			builder.WithParamDescription("Target OpenAPI version (2.0, 3.0, 3.1, 3.2)"),
			builder.WithParamRequired(true),
		),
		builder.WithResponse(http.StatusOK, ConvertResponse{},
			builder.WithResponseDescription("Conversion result with converted specification"),
		),
		builder.WithResponse(http.StatusBadRequest, ErrorResponse{},
			builder.WithResponseDescription("Invalid request or unparseable file"),
		),
		builder.WithResponse(http.StatusUnprocessableEntity, ErrorResponse{},
			builder.WithResponseDescription("Conversion failed"),
		),
		builder.WithHandler(h.handleConvert),
	)

	// POST /api/fix - automatically fix common issues in an OpenAPI specification
	srv.AddOperation(http.MethodPost, "/api/fix",
		builder.WithOperationID("fixSpec"),
		builder.WithSummary("Fix an OpenAPI specification"),
		builder.WithDescription("Automatically fixes common issues in an OpenAPI specification."),
		builder.WithTags("operations"),
		builder.WithFileParam("spec",
			builder.WithParamDescription("OpenAPI specification file (JSON or YAML)"),
			builder.WithParamRequired(true),
		),
		builder.WithFormParam("fixMissingParams", "boolean",
			builder.WithParamDescription("Add missing path parameters"),
		),
		builder.WithFormParam("removeUnusedSchemas", "boolean",
			builder.WithParamDescription("Remove unreferenced schemas"),
		),
		builder.WithFormParam("fixInvalidNames", "boolean",
			builder.WithParamDescription("Fix invalid schema names"),
		),
		builder.WithFormParam("pruneEmptyPaths", "boolean",
			builder.WithParamDescription("Remove empty paths"),
		),
		builder.WithResponse(http.StatusOK, FixResponse{},
			builder.WithResponseDescription("Fix result with fixed specification"),
		),
		builder.WithResponse(http.StatusBadRequest, ErrorResponse{},
			builder.WithResponseDescription("Invalid request or unparseable file"),
		),
		builder.WithResponse(http.StatusUnprocessableEntity, ErrorResponse{},
			builder.WithResponseDescription("Fix operation failed"),
		),
		builder.WithHandler(h.handleFix),
	)

	// POST /api/diff - compare two OpenAPI specifications
	srv.AddOperation(http.MethodPost, "/api/diff",
		builder.WithOperationID("diffSpecs"),
		builder.WithSummary("Compare two OpenAPI specifications"),
		builder.WithDescription("Compares two OpenAPI specifications and identifies additions, deletions, modifications, and breaking changes."),
		builder.WithTags("operations"),
		builder.WithFileParam("base",
			builder.WithParamDescription("Base (original) OpenAPI specification file"),
			builder.WithParamRequired(true),
		),
		builder.WithFileParam("head",
			builder.WithParamDescription("Head (modified) OpenAPI specification file"),
			builder.WithParamRequired(true),
		),
		builder.WithResponse(http.StatusOK, DiffResponse{},
			builder.WithResponseDescription("Diff result with list of changes"),
		),
		builder.WithResponse(http.StatusBadRequest, ErrorResponse{},
			builder.WithResponseDescription("Invalid request or unparseable files"),
		),
		builder.WithHandler(h.handleDiff),
	)

	// POST /api/join - merge multiple OpenAPI specifications
	srv.AddOperation(http.MethodPost, "/api/join",
		builder.WithOperationID("joinSpecs"),
		builder.WithSummary("Join multiple OpenAPI specifications"),
		builder.WithDescription("Merges 2-5 OpenAPI specifications into a single document with configurable collision handling."),
		builder.WithTags("operations"),
		builder.WithFileParam("specs",
			builder.WithParamDescription("OpenAPI specification files to merge (2-5 files)"),
			builder.WithParamRequired(true),
		),
		builder.WithFormParam("strategy", "string",
			builder.WithParamDescription("Collision strategy: rename, first, or error"),
		),
		builder.WithResponse(http.StatusOK, JoinResponse{},
			builder.WithResponseDescription("Join result with merged specification"),
		),
		builder.WithResponse(http.StatusBadRequest, ErrorResponse{},
			builder.WithResponseDescription("Invalid request or unparseable files"),
		),
		builder.WithResponse(http.StatusUnprocessableEntity, ErrorResponse{},
			builder.WithResponseDescription("Join operation failed"),
		),
		builder.WithHandler(h.handleJoin),
	)

	// POST /api/overlay - apply an OpenAPI Overlay to a specification
	srv.AddOperation(http.MethodPost, "/api/overlay",
		builder.WithOperationID("applyOverlay"),
		builder.WithSummary("Apply an OpenAPI Overlay"),
		builder.WithDescription("Applies an OpenAPI Overlay document to transform a specification."),
		builder.WithTags("operations"),
		builder.WithFileParam("spec",
			builder.WithParamDescription("OpenAPI specification file (JSON or YAML)"),
			builder.WithParamRequired(true),
		),
		builder.WithFileParam("overlay",
			builder.WithParamDescription("OpenAPI Overlay document (JSON or YAML)"),
			builder.WithParamRequired(true),
		),
		builder.WithResponse(http.StatusOK, OverlayResponse{},
			builder.WithResponseDescription("Overlay result with modified specification"),
		),
		builder.WithResponse(http.StatusBadRequest, ErrorResponse{},
			builder.WithResponseDescription("Invalid request or unparseable files"),
		),
		builder.WithResponse(http.StatusUnprocessableEntity, ErrorResponse{},
			builder.WithResponseDescription("Overlay application failed"),
		),
		builder.WithHandler(h.handleOverlay),
	)

	// POST /api/explore - upload and analyze an OpenAPI specification
	srv.AddOperation(http.MethodPost, "/api/explore",
		builder.WithOperationID("exploreUpload"),
		builder.WithSummary("Upload and analyze an OpenAPI specification"),
		builder.WithDescription("Parses and analyzes an OpenAPI specification, caching the result for subsequent exploration queries."),
		builder.WithTags("explore"),
		builder.WithFileParam("spec",
			builder.WithParamDescription("OpenAPI specification file (JSON or YAML)"),
			builder.WithParamRequired(true),
		),
		builder.WithResponse(http.StatusOK, nil,
			builder.WithResponseDescription("Analysis result with spec summary"),
		),
		builder.WithResponse(http.StatusBadRequest, ErrorResponse{},
			builder.WithResponseDescription("Invalid request or unparseable file"),
		),
		builder.WithHandler(h.handleExploreUpload),
	)

	// GET /api/explore/operations - retrieve operations from cached analysis
	srv.AddOperation(http.MethodGet, "/api/explore/operations",
		builder.WithOperationID("exploreOperations"),
		builder.WithSummary("Get operations from analyzed specification"),
		builder.WithDescription("Returns the list of operations from a previously analyzed specification."),
		builder.WithTags("explore"),
		builder.WithQueryParam("hash", "string",
			builder.WithParamDescription("Hash of the cached analysis"),
			builder.WithParamRequired(true),
		),
		builder.WithResponse(http.StatusOK, nil,
			builder.WithResponseDescription("Operations list"),
		),
		builder.WithResponse(http.StatusNotFound, ErrorResponse{},
			builder.WithResponseDescription("Analysis not found or expired"),
		),
		builder.WithHandler(h.handleExploreOperations),
	)

	// GET /api/explore/schemas - retrieve schemas from cached analysis
	srv.AddOperation(http.MethodGet, "/api/explore/schemas",
		builder.WithOperationID("exploreSchemas"),
		builder.WithSummary("Get schemas from analyzed specification"),
		builder.WithDescription("Returns the list of schemas from a previously analyzed specification."),
		builder.WithTags("explore"),
		builder.WithQueryParam("hash", "string",
			builder.WithParamDescription("Hash of the cached analysis"),
			builder.WithParamRequired(true),
		),
		builder.WithResponse(http.StatusOK, nil,
			builder.WithResponseDescription("Schemas list"),
		),
		builder.WithResponse(http.StatusNotFound, ErrorResponse{},
			builder.WithResponseDescription("Analysis not found or expired"),
		),
		builder.WithHandler(h.handleExploreSchemas),
	)

	// GET /api/explore/security - retrieve security schemes from cached analysis
	srv.AddOperation(http.MethodGet, "/api/explore/security",
		builder.WithOperationID("exploreSecurity"),
		builder.WithSummary("Get security schemes from analyzed specification"),
		builder.WithDescription("Returns the security schemes from a previously analyzed specification."),
		builder.WithTags("explore"),
		builder.WithQueryParam("hash", "string",
			builder.WithParamDescription("Hash of the cached analysis"),
			builder.WithParamRequired(true),
		),
		builder.WithResponse(http.StatusOK, nil,
			builder.WithResponseDescription("Security schemes list"),
		),
		builder.WithResponse(http.StatusNotFound, ErrorResponse{},
			builder.WithResponseDescription("Analysis not found or expired"),
		),
		builder.WithHandler(h.handleExploreSecurity),
	)

	// GET /api/explore/operation - retrieve operation details from cached analysis
	srv.AddOperation(http.MethodGet, "/api/explore/operation",
		builder.WithOperationID("exploreOperationDetail"),
		builder.WithSummary("Get operation details from analyzed specification"),
		builder.WithDescription("Returns the full details of a specific operation from a previously analyzed specification."),
		builder.WithTags("explore"),
		builder.WithQueryParam("h", "string",
			builder.WithParamDescription("Hash of the cached analysis"),
			builder.WithParamRequired(true),
		),
		builder.WithQueryParam("path", "string",
			builder.WithParamDescription("Path template of the operation"),
			builder.WithParamRequired(true),
		),
		builder.WithQueryParam("method", "string",
			builder.WithParamDescription("HTTP method of the operation"),
			builder.WithParamRequired(true),
		),
		builder.WithResponse(http.StatusOK, nil,
			builder.WithResponseDescription("Operation details"),
		),
		builder.WithResponse(http.StatusBadRequest, ErrorResponse{},
			builder.WithResponseDescription("Missing required parameters"),
		),
		builder.WithResponse(http.StatusNotFound, ErrorResponse{},
			builder.WithResponseDescription("Operation or analysis not found"),
		),
		builder.WithResponse(http.StatusGone, nil,
			builder.WithResponseDescription("Analysis cache expired"),
		),
		builder.WithHandler(h.handleExploreOperationDetail),
	)

	// GET /api/explore/schema - retrieve schema details from cached analysis
	srv.AddOperation(http.MethodGet, "/api/explore/schema",
		builder.WithOperationID("exploreSchemaDetail"),
		builder.WithSummary("Get schema details from analyzed specification"),
		builder.WithDescription("Returns the full details of a specific schema from a previously analyzed specification."),
		builder.WithTags("explore"),
		builder.WithQueryParam("h", "string",
			builder.WithParamDescription("Hash of the cached analysis"),
			builder.WithParamRequired(true),
		),
		builder.WithQueryParam("name", "string",
			builder.WithParamDescription("Name of the schema"),
			builder.WithParamRequired(true),
		),
		builder.WithResponse(http.StatusOK, nil,
			builder.WithResponseDescription("Schema details"),
		),
		builder.WithResponse(http.StatusBadRequest, ErrorResponse{},
			builder.WithResponseDescription("Missing required parameters"),
		),
		builder.WithResponse(http.StatusNotFound, ErrorResponse{},
			builder.WithResponseDescription("Schema or analysis not found"),
		),
		builder.WithResponse(http.StatusGone, nil,
			builder.WithResponseDescription("Analysis cache expired"),
		),
		builder.WithHandler(h.handleExploreSchemaDetail),
	)

	// GET /api/explore/inline-schemas - retrieve inline schema locations from cached analysis
	srv.AddOperation(http.MethodGet, "/api/explore/inline-schemas",
		builder.WithOperationID("exploreInlineSchemas"),
		builder.WithSummary("Get inline schema locations from analyzed specification"),
		builder.WithDescription("Returns the locations of all inline schemas from a previously analyzed specification."),
		builder.WithTags("explore"),
		builder.WithQueryParam("h", "string",
			builder.WithParamDescription("Hash of the cached analysis"),
			builder.WithParamRequired(true),
		),
		builder.WithResponse(http.StatusOK, nil,
			builder.WithResponseDescription("Inline schema locations"),
		),
		builder.WithResponse(http.StatusBadRequest, ErrorResponse{},
			builder.WithResponseDescription("Missing hash parameter"),
		),
		builder.WithResponse(http.StatusGone, nil,
			builder.WithResponseDescription("Analysis cache expired"),
		),
		builder.WithHandler(h.handleExploreInlineSchemas),
	)

	// GET /api/explore/security-detail - retrieve security scheme details from cached analysis
	srv.AddOperation(http.MethodGet, "/api/explore/security-detail",
		builder.WithOperationID("exploreSecurityDetail"),
		builder.WithSummary("Get security scheme details from analyzed specification"),
		builder.WithDescription("Returns the full details of a specific security scheme including which operations use it."),
		builder.WithTags("explore"),
		builder.WithQueryParam("h", "string",
			builder.WithParamDescription("Hash of the cached analysis"),
			builder.WithParamRequired(true),
		),
		builder.WithQueryParam("name", "string",
			builder.WithParamDescription("Name of the security scheme"),
			builder.WithParamRequired(true),
		),
		builder.WithResponse(http.StatusOK, nil,
			builder.WithResponseDescription("Security scheme details"),
		),
		builder.WithResponse(http.StatusBadRequest, ErrorResponse{},
			builder.WithResponseDescription("Missing required parameters"),
		),
		builder.WithResponse(http.StatusNotFound, ErrorResponse{},
			builder.WithResponseDescription("Security scheme not found"),
		),
		builder.WithResponse(http.StatusGone, nil,
			builder.WithResponseDescription("Analysis cache expired"),
		),
		builder.WithHandler(h.handleExploreSecurityDetail),
	)

	// GET /api/explore/unsecured - retrieve unsecured operations from cached analysis
	srv.AddOperation(http.MethodGet, "/api/explore/unsecured",
		builder.WithOperationID("exploreUnsecured"),
		builder.WithSummary("Get unsecured operations from analyzed specification"),
		builder.WithDescription("Returns all operations that have no security requirements."),
		builder.WithTags("explore"),
		builder.WithQueryParam("h", "string",
			builder.WithParamDescription("Hash of the cached analysis"),
			builder.WithParamRequired(true),
		),
		builder.WithResponse(http.StatusOK, nil,
			builder.WithResponseDescription("List of unsecured operations"),
		),
		builder.WithResponse(http.StatusBadRequest, ErrorResponse{},
			builder.WithResponseDescription("Missing hash parameter"),
		),
		builder.WithResponse(http.StatusGone, nil,
			builder.WithResponseDescription("Analysis cache expired"),
		),
		builder.WithHandler(h.handleExploreUnsecured),
	)

	// GET /api/explore/summary-details - retrieve expanded summary statistics from cached analysis
	srv.AddOperation(http.MethodGet, "/api/explore/summary-details",
		builder.WithOperationID("exploreSummaryDetails"),
		builder.WithSummary("Get expanded summary statistics from analyzed specification"),
		builder.WithDescription("Returns detailed breakdown of methods, schemas, and security coverage."),
		builder.WithTags("explore"),
		builder.WithQueryParam("h", "string",
			builder.WithParamDescription("Hash of the cached analysis"),
			builder.WithParamRequired(true),
		),
		builder.WithResponse(http.StatusOK, nil,
			builder.WithResponseDescription("Expanded summary statistics"),
		),
		builder.WithResponse(http.StatusBadRequest, ErrorResponse{},
			builder.WithResponseDescription("Missing hash parameter"),
		),
		builder.WithResponse(http.StatusGone, nil,
			builder.WithResponseDescription("Analysis cache expired"),
		),
		builder.WithHandler(h.handleExploreSummaryDetails),
	)
}
